env:
  node: true

extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
  - prettier # should come last

parser: '@typescript-eslint/parser'

plugins:
  - '@typescript-eslint'

root: true

rules:
  '@typescript-eslint/no-var-requires': off
