arrowParens: avoid
bracketSameLine: false
bracketSpacing: true
endOfLine: lf
htmlWhitespaceSensitivity: css
insertPragma: false
jsxSingleQuote: false
# see: https://prettier.io/docs/en/configuration.html#setting-the-parserdocsenoptionshtmlparser-option
overrides:
  - files: ['*.webc']
    options:
      parser: 'html'
# see: https://prettier.io/docs/en/plugins.html
plugins: ['prettier-plugin-toml']
printWidth: 100
proseWrap: preserve
quoteProps: as-needed
requirePragma: false
semi: true
singleQuote: true
tabWidth: 2
trailingComma: all
useTabs: false
