# Builds the site on GitHub because GitHub offers 2000 free CI/CD minutes, while Netlify offers 300.
# See: https://bennypowers.dev/posts/cheap-netlify-11ty-rebuilds/

name: Rebuild Netlify site

on:
  push:
    branches:
      - main

jobs:
  rebuild:
    runs-on: ubuntu-latest
    name: Rebuild site
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      # use cached node_modules if found (instead of running npm install)
      - run: npm ci --prefer-offline
      - run: npm run build

      - name: Publish to Netlify
        env:
          # Netlify settings "Site name"
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          # Netlify personal access token created here: https://app.netlify.com/user/applications
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        # Deploy updated "_site" folder to production Netlify branch
        run: npx netlify-cli deploy --prod --message "deploy from GitHub Action" --dir=_site
